"""Add PayTransfer and Payroll models

Revision ID: 03759f934af2
Revises: a72cec5ac0f3
Create Date: 2025-07-02 11:25:22.477623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03759f934af2'
down_revision = 'a72cec5ac0f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pay_transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_user_id', sa.Integer(), nullable=False),
    sa.Column('to_user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pay_transfers', schema=None) as batch_op:
        batch_op.create_index('idx_transfer_status', ['status', 'created_at'], unique=False)
        batch_op.create_index('idx_transfer_users', ['from_user_id', 'to_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pay_transfers_completed_at'), ['completed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_pay_transfers_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_pay_transfers_from_user_id'), ['from_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pay_transfers_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_pay_transfers_to_user_id'), ['to_user_id'], unique=False)

    op.create_table('payrolls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('base_salary', sa.Integer(), nullable=True),
    sa.Column('allowance', sa.Integer(), nullable=True),
    sa.Column('deduction', sa.Integer(), nullable=True),
    sa.Column('net_salary', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'year', 'month', name='uq_user_year_month')
    )
    with op.batch_alter_table('payrolls', schema=None) as batch_op:
        batch_op.create_index('idx_payroll_user_period', ['user_id', 'year', 'month'], unique=False)
        batch_op.create_index(batch_op.f('ix_payrolls_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payrolls_month'), ['month'], unique=False)
        batch_op.create_index(batch_op.f('ix_payrolls_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payrolls_year'), ['year'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payrolls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payrolls_year'))
        batch_op.drop_index(batch_op.f('ix_payrolls_user_id'))
        batch_op.drop_index(batch_op.f('ix_payrolls_month'))
        batch_op.drop_index(batch_op.f('ix_payrolls_created_at'))
        batch_op.drop_index('idx_payroll_user_period')

    op.drop_table('payrolls')
    with op.batch_alter_table('pay_transfers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pay_transfers_to_user_id'))
        batch_op.drop_index(batch_op.f('ix_pay_transfers_status'))
        batch_op.drop_index(batch_op.f('ix_pay_transfers_from_user_id'))
        batch_op.drop_index(batch_op.f('ix_pay_transfers_created_at'))
        batch_op.drop_index(batch_op.f('ix_pay_transfers_completed_at'))
        batch_op.drop_index('idx_transfer_users')
        batch_op.drop_index('idx_transfer_status')

    op.drop_table('pay_transfers')
    # ### end Alembic commands ###
