"""Add NoticeComment

Revision ID: 039947c85d61
Revises: 5ce06769cd21
Create Date: 2025-06-20 14:23:18.173974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '039947c85d61'
down_revision = '5ce06769cd21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notices', schema=None) as batch_op:
        batch_op.create_index('idx_notice_author_date', ['author_id', 'created_at'], unique=False)
        batch_op.create_index('idx_notice_category_date', ['category', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notices_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notices_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_notices_created_at'), ['created_at'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('idx_notification_created', ['created_at'], unique=False)
        batch_op.create_index('idx_notification_user_read', ['user_id', 'is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('shift_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('request_date', sa.Date(), nullable=False),
    sa.Column('desired_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shift_requests', schema=None) as batch_op:
        batch_op.create_index('idx_shiftrequest_date_range', ['request_date', 'desired_date'], unique=False)
        batch_op.create_index('idx_shiftrequest_user_status', ['user_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_shift_requests_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_shift_requests_desired_date'), ['desired_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_shift_requests_request_date'), ['request_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_shift_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_shift_requests_user_id'), ['user_id'], unique=False)

    op.create_table('notice_reads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notice_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['notice_id'], ['notices.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notice_reads', schema=None) as batch_op:
        batch_op.create_index('idx_noticeread_notice_date', ['notice_id', 'read_at'], unique=False)
        batch_op.create_index('idx_noticeread_user_notice', ['user_id', 'notice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notice_reads_notice_id'), ['notice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notice_reads_read_at'), ['read_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notice_reads_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('action_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_address', sa.String(length=45), nullable=True))
        batch_op.add_column(sa.Column('user_agent', sa.String(length=200), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('action',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.create_index('idx_actionlog_action_date', ['action', 'created_at'], unique=False)
        batch_op.create_index('idx_actionlog_user_action', ['user_id', 'action'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_logs_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_action_logs_user', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('approve_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_address', sa.String(length=45), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('action',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
        batch_op.alter_column('admin_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_index('idx_approvelog_admin_date', ['admin_id', 'timestamp'], unique=False)
        batch_op.create_index('idx_approvelog_user_action', ['user_id', 'action'], unique=False)
        batch_op.create_index(batch_op.f('ix_approve_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_approve_logs_admin_id'), ['admin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approve_logs_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_approve_logs_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_in', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('location_out', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('clock_in',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index('idx_attendance_date_range', ['clock_in', 'clock_out'], unique=False)
        batch_op.create_index('idx_attendance_user_date', ['user_id', 'clock_in'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendances_clock_in'), ['clock_in'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendances_clock_out'), ['clock_out'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendances_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendances_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_branches_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_branches_name'), ['name'], unique=True)

    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('comment',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_feedback_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('login_attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('locked_until', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_last_login'), ['last_login'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_locked_until'), ['locked_until'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_status'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_locked_until'))
        batch_op.drop_index(batch_op.f('ix_users_last_login'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))
        batch_op.drop_index(batch_op.f('ix_users_branch_id'))
        batch_op.drop_column('locked_until')
        batch_op.drop_column('login_attempts')
        batch_op.drop_column('last_login')
        batch_op.drop_column('email')

    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_user_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_created_at'))
        batch_op.alter_column('comment',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('category')

    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_branches_name'))
        batch_op.drop_index(batch_op.f('ix_branches_created_at'))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('phone')
        batch_op.drop_column('address')

    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendances_user_id'))
        batch_op.drop_index(batch_op.f('ix_attendances_created_at'))
        batch_op.drop_index(batch_op.f('ix_attendances_clock_out'))
        batch_op.drop_index(batch_op.f('ix_attendances_clock_in'))
        batch_op.drop_index('idx_attendance_user_date')
        batch_op.drop_index('idx_attendance_date_range')
        batch_op.alter_column('clock_in',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('notes')
        batch_op.drop_column('location_out')
        batch_op.drop_column('location_in')

    with op.batch_alter_table('approve_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approve_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_approve_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_approve_logs_admin_id'))
        batch_op.drop_index(batch_op.f('ix_approve_logs_action'))
        batch_op.drop_index('idx_approvelog_user_action')
        batch_op.drop_index('idx_approvelog_admin_date')
        batch_op.alter_column('admin_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('action',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('ip_address')

    with op.batch_alter_table('action_logs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_action_logs_user', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_action_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_action_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_action_logs_action'))
        batch_op.drop_index('idx_actionlog_user_action')
        batch_op.drop_index('idx_actionlog_action_date')
        batch_op.alter_column('action',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('user_agent')
        batch_op.drop_column('ip_address')

    with op.batch_alter_table('notice_reads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notice_reads_user_id'))
        batch_op.drop_index(batch_op.f('ix_notice_reads_read_at'))
        batch_op.drop_index(batch_op.f('ix_notice_reads_notice_id'))
        batch_op.drop_index('idx_noticeread_user_notice')
        batch_op.drop_index('idx_noticeread_notice_date')

    op.drop_table('notice_reads')
    with op.batch_alter_table('shift_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shift_requests_user_id'))
        batch_op.drop_index(batch_op.f('ix_shift_requests_status'))
        batch_op.drop_index(batch_op.f('ix_shift_requests_request_date'))
        batch_op.drop_index(batch_op.f('ix_shift_requests_desired_date'))
        batch_op.drop_index(batch_op.f('ix_shift_requests_created_at'))
        batch_op.drop_index('idx_shiftrequest_user_status')
        batch_op.drop_index('idx_shiftrequest_date_range')

    op.drop_table('shift_requests')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_is_read'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))
        batch_op.drop_index('idx_notification_user_read')
        batch_op.drop_index('idx_notification_created')

    op.drop_table('notifications')
    with op.batch_alter_table('notices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notices_created_at'))
        batch_op.drop_index(batch_op.f('ix_notices_category'))
        batch_op.drop_index(batch_op.f('ix_notices_author_id'))
        batch_op.drop_index('idx_notice_category_date')
        batch_op.drop_index('idx_notice_author_date')

    op.drop_table('notices')
    # ### end Alembic commands ###
