"""Add failed_login column to User model

Revision ID: 1039f7ad8712
Revises: 34ebbe1452d4
Create Date: 2025-06-20 20:24:29.590436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1039f7ad8712'
down_revision = '34ebbe1452d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('suggestions', schema=None) as batch_op:
        batch_op.create_index('idx_suggestion_answered', ['answered_at'], unique=False)
        batch_op.create_index('idx_suggestion_created', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_suggestions_answered_at'), ['answered_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_suggestions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_suggestions_is_anonymous'), ['is_anonymous'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=10), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('admin_comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index('idx_report_category', ['category'], unique=False)
        batch_op.create_index('idx_report_status_date', ['status', 'created_at'], unique=False)
        batch_op.create_index('idx_report_target', ['target_type', 'target_id'], unique=False)
        batch_op.create_index('idx_report_user_date', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_reviewed_at'), ['reviewed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_reviewed_by'), ['reviewed_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_target_type'), ['target_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_user_id'), ['user_id'], unique=False)

    op.create_table('system_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('detail', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notice_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notice_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['notice_id'], ['notices.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notice_comments', schema=None) as batch_op:
        batch_op.create_index('idx_comment_hidden_date', ['is_hidden', 'created_at'], unique=False)
        batch_op.create_index('idx_comment_notice_date', ['notice_id', 'created_at'], unique=False)
        batch_op.create_index('idx_comment_user_date', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notice_comments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notice_comments_is_hidden'), ['is_hidden'], unique=False)
        batch_op.create_index(batch_op.f('ix_notice_comments_notice_id'), ['notice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notice_comments_user_id'), ['user_id'], unique=False)

    op.create_table('notice_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notice_id', sa.Integer(), nullable=False),
    sa.Column('editor_id', sa.Integer(), nullable=False),
    sa.Column('before_title', sa.String(length=100), nullable=True),
    sa.Column('before_content', sa.Text(), nullable=True),
    sa.Column('before_file_path', sa.String(length=255), nullable=True),
    sa.Column('before_file_type', sa.String(length=20), nullable=True),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.Column('action', sa.String(length=10), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['editor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['notice_id'], ['notices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notice_histories', schema=None) as batch_op:
        batch_op.create_index('idx_history_action_date', ['action', 'edited_at'], unique=False)
        batch_op.create_index('idx_history_editor_date', ['editor_id', 'edited_at'], unique=False)
        batch_op.create_index('idx_history_notice_date', ['notice_id', 'edited_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notice_histories_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_notice_histories_edited_at'), ['edited_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notice_histories_editor_id'), ['editor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notice_histories_notice_id'), ['notice_id'], unique=False)

    op.create_table('comment_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('editor_id', sa.Integer(), nullable=False),
    sa.Column('before_content', sa.Text(), nullable=True),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.Column('action', sa.String(length=10), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['notice_comments.id'], ),
    sa.ForeignKeyConstraint(['editor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comment_histories', schema=None) as batch_op:
        batch_op.create_index('idx_comment_history_action_date', ['action', 'edited_at'], unique=False)
        batch_op.create_index('idx_comment_history_comment_date', ['comment_id', 'edited_at'], unique=False)
        batch_op.create_index('idx_comment_history_editor_date', ['editor_id', 'edited_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_comment_histories_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_comment_histories_comment_id'), ['comment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comment_histories_edited_at'), ['edited_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_comment_histories_editor_id'), ['editor_id'], unique=False)

    with op.batch_alter_table('notices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('is_hidden', sa.Boolean(), nullable=True))
        batch_op.create_index('idx_notice_hidden_date', ['is_hidden', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notices_is_hidden'), ['is_hidden'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('failed_login', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('failed_login')

    with op.batch_alter_table('notices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notices_is_hidden'))
        batch_op.drop_index('idx_notice_hidden_date')
        batch_op.drop_column('is_hidden')
        batch_op.drop_column('file_type')

    with op.batch_alter_table('comment_histories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comment_histories_editor_id'))
        batch_op.drop_index(batch_op.f('ix_comment_histories_edited_at'))
        batch_op.drop_index(batch_op.f('ix_comment_histories_comment_id'))
        batch_op.drop_index(batch_op.f('ix_comment_histories_action'))
        batch_op.drop_index('idx_comment_history_editor_date')
        batch_op.drop_index('idx_comment_history_comment_date')
        batch_op.drop_index('idx_comment_history_action_date')

    op.drop_table('comment_histories')
    with op.batch_alter_table('notice_histories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notice_histories_notice_id'))
        batch_op.drop_index(batch_op.f('ix_notice_histories_editor_id'))
        batch_op.drop_index(batch_op.f('ix_notice_histories_edited_at'))
        batch_op.drop_index(batch_op.f('ix_notice_histories_action'))
        batch_op.drop_index('idx_history_notice_date')
        batch_op.drop_index('idx_history_editor_date')
        batch_op.drop_index('idx_history_action_date')

    op.drop_table('notice_histories')
    with op.batch_alter_table('notice_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notice_comments_user_id'))
        batch_op.drop_index(batch_op.f('ix_notice_comments_notice_id'))
        batch_op.drop_index(batch_op.f('ix_notice_comments_is_hidden'))
        batch_op.drop_index(batch_op.f('ix_notice_comments_created_at'))
        batch_op.drop_index('idx_comment_user_date')
        batch_op.drop_index('idx_comment_notice_date')
        batch_op.drop_index('idx_comment_hidden_date')

    op.drop_table('notice_comments')
    op.drop_table('system_log')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_user_id'))
        batch_op.drop_index(batch_op.f('ix_reports_target_type'))
        batch_op.drop_index(batch_op.f('ix_reports_target_id'))
        batch_op.drop_index(batch_op.f('ix_reports_status'))
        batch_op.drop_index(batch_op.f('ix_reports_reviewed_by'))
        batch_op.drop_index(batch_op.f('ix_reports_reviewed_at'))
        batch_op.drop_index(batch_op.f('ix_reports_created_at'))
        batch_op.drop_index(batch_op.f('ix_reports_category'))
        batch_op.drop_index('idx_report_user_date')
        batch_op.drop_index('idx_report_target')
        batch_op.drop_index('idx_report_status_date')
        batch_op.drop_index('idx_report_category')

    op.drop_table('reports')
    with op.batch_alter_table('suggestions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suggestions_is_anonymous'))
        batch_op.drop_index(batch_op.f('ix_suggestions_created_at'))
        batch_op.drop_index(batch_op.f('ix_suggestions_answered_at'))
        batch_op.drop_index('idx_suggestion_created')
        batch_op.drop_index('idx_suggestion_answered')

    op.drop_table('suggestions')
    # ### end Alembic commands ###
