"""add_category_and_link_to_notifications

Revision ID: 11ef276d8ea8
Revises: 98cdd15f7497
Create Date: 2025-06-23 09:14:16.803005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11ef276d8ea8'
down_revision = '98cdd15f7497'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('link', sa.String(length=255), nullable=True))
        batch_op.drop_index('idx_notification_created')
        batch_op.create_index('idx_notification_category_date', ['category', 'created_at'], unique=False)
        batch_op.create_index('idx_notification_user_category', ['user_id', 'category'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_category'), ['category'], unique=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('detail', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('detail')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_category'))
        batch_op.drop_index('idx_notification_user_category')
        batch_op.drop_index('idx_notification_category_date')
        batch_op.create_index('idx_notification_created', ['created_at'], unique=False)
        batch_op.drop_column('link')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
