"""Add IndustryAdmin model and enhanced monitoring tables

Revision ID: 172d724fdfe6
Revises: ba33e346a1a4
Create Date: 2025-07-28 17:37:54.316701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '172d724fdfe6'
down_revision = 'ba33e346a1a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plugin_reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))
        batch_op.alter_column('plugin_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'plugins', ['plugin_id'], ['id'])
        batch_op.drop_column('version')

    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hire_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_staff_your_program_id'))
        batch_op.create_index(batch_op.f('ix_staff_branch_id'), ['branch_id'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'branches', ['branch_id'], ['id'])
        batch_op.drop_column('join_date')
        batch_op.drop_column('your_program_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('your_program_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('join_date', sa.DATE(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'branches', ['your_program_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_staff_branch_id'))
        batch_op.create_index(batch_op.f('ix_staff_your_program_id'), ['your_program_id'], unique=False)
        batch_op.drop_column('branch_id')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('hire_date')

    with op.batch_alter_table('plugin_reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.VARCHAR(length=20), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'modules', ['plugin_id'], ['id'])
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('plugin_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('is_verified')

    # ### end Alembic commands ###
