"""Add staff templates and registration steps

Revision ID: 1c9fb5e17d1d
Revises: c42569c9af83
Create Date: 2025-07-06 19:54:26.924393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c9fb5e17d1d'
down_revision = 'c42569c9af83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('position', sa.String(length=50), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=False),
    sa.Column('template_type', sa.String(length=20), nullable=True),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('salary_base', sa.Integer(), nullable=True),
    sa.Column('work_days', sa.JSON(), nullable=True),
    sa.Column('work_hours_start', sa.String(length=5), nullable=True),
    sa.Column('work_hours_end', sa.String(length=5), nullable=True),
    sa.Column('benefits', sa.JSON(), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('required_documents', sa.JSON(), nullable=True),
    sa.Column('probation_period', sa.Integer(), nullable=True),
    sa.Column('notice_period', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff_registration_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('step1_completed', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('position', sa.String(length=50), nullable=True),
    sa.Column('department', sa.String(length=50), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('step2_completed', sa.Boolean(), nullable=True),
    sa.Column('work_days', sa.JSON(), nullable=True),
    sa.Column('work_hours_start', sa.String(length=5), nullable=True),
    sa.Column('work_hours_end', sa.String(length=5), nullable=True),
    sa.Column('salary_base', sa.Integer(), nullable=True),
    sa.Column('salary_allowance', sa.Integer(), nullable=True),
    sa.Column('salary_bonus', sa.Integer(), nullable=True),
    sa.Column('benefits', sa.JSON(), nullable=True),
    sa.Column('step3_completed', sa.Boolean(), nullable=True),
    sa.Column('health_certificate_issue_date', sa.Date(), nullable=True),
    sa.Column('health_certificate_expiry_date', sa.Date(), nullable=True),
    sa.Column('health_certificate_renewal_date', sa.Date(), nullable=True),
    sa.Column('required_documents', sa.JSON(), nullable=True),
    sa.Column('step4_completed', sa.Boolean(), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['staff_templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('staff_registration_steps')
    op.drop_table('staff_templates')
    # ### end Alembic commands ###
