"""Add SystemLog model

Revision ID: 34ebbe1452d4
Revises: e35e4092e71b
Create Date: 2025-06-20 16:04:24.246704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34ebbe1452d4'
down_revision = 'e35e4092e71b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('detail', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_notice_category_date'))
        batch_op.create_index('idx_notice_category', ['category'], unique=False)
        batch_op.create_index('idx_notice_content', ['content'], unique=False)
        batch_op.create_index('idx_notice_title', ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notices', schema=None) as batch_op:
        batch_op.drop_index('idx_notice_title')
        batch_op.drop_index('idx_notice_content')
        batch_op.drop_index('idx_notice_category')
        batch_op.create_index(batch_op.f('idx_notice_category_date'), ['category', 'created_at'], unique=False)

    op.drop_table('system_log')
    # ### end Alembic commands ###
