"""주문 처리 시간 필드 확인 및 정리

Revision ID: 3c454746626d
Revises: b0ccf3e62f41
Create Date: 2025-06-29 09:42:27.440984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c454746626d'
down_revision = 'b0ccf3e62f41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_branches')
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('processing_time_standard', sa.Integer(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=128),
               nullable=True)
        batch_op.drop_index('ix_branches_name')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('processing_minutes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('employee_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('store_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_orders_employee_id', 'users', ['employee_id'], ['id'])
        batch_op.create_foreign_key('fk_orders_store_id', 'branches', ['store_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('fk_orders_employee_id', type_='foreignkey')
        batch_op.drop_constraint('fk_orders_store_id', type_='foreignkey')
        batch_op.drop_column('store_id')
        batch_op.drop_column('employee_id')
        batch_op.drop_column('processing_minutes')
        batch_op.drop_column('completed_at')

    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.create_index('ix_branches_name', ['name'], unique=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('processing_time_standard')

    op.create_table('_alembic_tmp_branches',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=True),
    sa.Column('address', sa.VARCHAR(length=200), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('processing_time_standard', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
