"""add_reason_template_model

Revision ID: 418c372cfb07
Revises: 4ed3893fc675
Create Date: 2025-06-24 18:51:20.783493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '418c372cfb07'
down_revision = '4ed3893fc675'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reason_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='템플릿명'),
    sa.Column('value', sa.String(length=200), nullable=False, comment='사유 내용'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='카테고리'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='활성화 여부'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='생성자'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='수정일시'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attendance_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.alter_column('period_from',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Date(),
               existing_nullable=False)
        batch_op.alter_column('period_to',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Date(),
               existing_nullable=False)
        batch_op.alter_column('grade',
               existing_type=sa.VARCHAR(length=2),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.alter_column('comment',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.drop_index('idx_attendance_report_grade')
        batch_op.drop_index('idx_attendance_report_score')
        batch_op.drop_index('idx_attendance_report_user_period')
        batch_op.drop_index('ix_attendance_reports_created_at')
        batch_op.drop_index('ix_attendance_reports_user_id')
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_reports', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('ix_attendance_reports_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_attendance_reports_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_attendance_report_user_period', ['user_id', 'period_from', 'period_to'], unique=False)
        batch_op.create_index('idx_attendance_report_score', ['score'], unique=False)
        batch_op.create_index('idx_attendance_report_grade', ['grade'], unique=False)
        batch_op.alter_column('comment',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)
        batch_op.alter_column('grade',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=2),
               existing_nullable=True)
        batch_op.alter_column('period_to',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
        batch_op.alter_column('period_from',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
        batch_op.drop_column('created_by')

    op.drop_table('reason_templates')
    # ### end Alembic commands ###
