"""Add brand_id to SystemLog, Schedule, CleaningPlan, Team, PayTransfer, AIIntegration

Revision ID: 48d7b69d23b4
Revises: ad1fb0b00a4c
Create Date: 2025-07-15 20:32:54.433062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48d7b69d23b4'
down_revision = 'ad1fb0b00a4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_integrations', schema=None) as batch_op:
        # brand_id 외래키 및 인덱스 추가 (제약조건 이름 명시)
        batch_op.add_column(sa.Column('brand_id', sa.Integer(), nullable=True))
        batch_op.create_index('ix_ai_integrations_brand_id', ['brand_id'], unique=False)
        batch_op.create_foreign_key('fk_ai_integrations_brand_id', 'brands', ['brand_id'], ['id'])

    with op.batch_alter_table('cleaning_plan', schema=None) as batch_op:
        # brand_id 외래키 및 인덱스 추가 (제약조건 이름 명시)
        batch_op.add_column(sa.Column('brand_id', sa.Integer(), nullable=True))
        batch_op.create_index('ix_cleaning_plan_brand_id', ['brand_id'], unique=False)
        batch_op.create_foreign_key('fk_cleaning_plan_brand_id', 'brands', ['brand_id'], ['id'])

    with op.batch_alter_table('pay_transfers', schema=None) as batch_op:
        # brand_id 외래키 및 인덱스 추가 (제약조건 이름 명시)
        batch_op.add_column(sa.Column('brand_id', sa.Integer(), nullable=True))
        batch_op.create_index('ix_pay_transfers_brand_id', ['brand_id'], unique=False)
        batch_op.create_foreign_key('fk_pay_transfers_brand_id', 'brands', ['brand_id'], ['id'])

    with op.batch_alter_table('schedule', schema=None) as batch_op:
        # brand_id 외래키 및 인덱스 추가 (제약조건 이름 명시)
        batch_op.add_column(sa.Column('brand_id', sa.Integer(), nullable=True))
        batch_op.create_index('ix_schedule_brand_id', ['brand_id'], unique=False)
        batch_op.create_foreign_key('fk_schedule_brand_id', 'brands', ['brand_id'], ['id'])

    with op.batch_alter_table('system_logs', schema=None) as batch_op:
        # brand_id 외래키 및 인덱스 추가 (제약조건 이름 명시)
        batch_op.add_column(sa.Column('brand_id', sa.Integer(), nullable=True))
        batch_op.create_index('ix_system_logs_brand_id', ['brand_id'], unique=False)
        batch_op.create_foreign_key('fk_system_logs_brand_id', 'brands', ['brand_id'], ['id'])

    with op.batch_alter_table('teams', schema=None) as batch_op:
        # brand_id 외래키 및 인덱스 추가 (제약조건 이름 명시)
        batch_op.add_column(sa.Column('brand_id', sa.Integer(), nullable=True))
        batch_op.create_index('ix_teams_brand_id', ['brand_id'], unique=False)
        batch_op.create_foreign_key('fk_teams_brand_id', 'brands', ['brand_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('login_attempts', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('login_attempts')

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_teams_brand_id'))
        batch_op.drop_column('brand_id')

    with op.batch_alter_table('system_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_system_logs_brand_id'))
        batch_op.drop_column('brand_id')

    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_schedule_brand_id'))
        batch_op.drop_column('brand_id')

    with op.batch_alter_table('pay_transfers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_pay_transfers_brand_id'))
        batch_op.drop_column('brand_id')

    with op.batch_alter_table('cleaning_plan', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_cleaning_plan_brand_id'))
        batch_op.drop_column('brand_id')

    with op.batch_alter_table('ai_integrations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_ai_integrations_brand_id'))
        batch_op.drop_column('brand_id')

    # ### end Alembic commands ###
