"""Add attendance report model

Revision ID: 4d992cbb260c
Revises: 2977c664f7ab
Create Date: 2025-06-24 09:30:25.893298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d992cbb260c'
down_revision = '2977c664f7ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('period_from', sa.String(length=10), nullable=False),
    sa.Column('period_to', sa.String(length=10), nullable=False),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('late', sa.Integer(), nullable=True),
    sa.Column('early', sa.Integer(), nullable=True),
    sa.Column('ot', sa.Integer(), nullable=True),
    sa.Column('ontime', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('grade', sa.String(length=2), nullable=True),
    sa.Column('comment', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attendance_reports', schema=None) as batch_op:
        batch_op.create_index('idx_attendance_report_grade', ['grade'], unique=False)
        batch_op.create_index('idx_attendance_report_score', ['score'], unique=False)
        batch_op.create_index('idx_attendance_report_user_period', ['user_id', 'period_from', 'period_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_reports_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_reports_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_reports_user_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_reports_created_at'))
        batch_op.drop_index('idx_attendance_report_user_period')
        batch_op.drop_index('idx_attendance_report_score')
        batch_op.drop_index('idx_attendance_report_grade')

    op.drop_table('attendance_reports')
    # ### end Alembic commands ###
