"""add_reason_to_attendance

Revision ID: 4ed3893fc675
Revises: 4d992cbb260c
Create Date: 2025-06-24 16:00:48.048264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ed3893fc675'
down_revision = '4d992cbb260c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reason', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.drop_column('reason')

    # ### end Alembic commands ###
