"""Add department column to users table

Revision ID: 6d07eca14f89
Revises: a08fedabe0c4
Create Date: 2025-07-06 12:39:37.832025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d07eca14f89'
down_revision = 'a08fedabe0c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_department'), ['department'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_department'))
        batch_op.drop_column('department')

    # ### end Alembic commands ###
