"""Add status to Schedule and create Notification model

Revision ID: 77097a1f5019
Revises: b50513fa2be6
Create Date: 2025-06-22 12:58:24.417793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77097a1f5019'
down_revision = 'b50513fa2be6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cleaning_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.alter_column('plan',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.create_foreign_key('fk_cleaning_plan_user', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('related_url', sa.String(length=255), nullable=True))
        batch_op.drop_column('message')

    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True, server_default='대기'))

    op.execute("UPDATE schedule SET status = '대기' WHERE status IS NULL")

    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               nullable=False,
               existing_server_default='대기')
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'근무'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'근무'"))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('related_url')
        batch_op.drop_column('content')

    with op.batch_alter_table('cleaning_plan', schema=None) as batch_op:
        batch_op.drop_constraint('fk_cleaning_plan_user', type_='foreignkey')
        batch_op.alter_column('plan',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
