"""add order request

Revision ID: 89734f39cd32
Revises: 3c454746626d
Create Date: 2025-06-29 13:10:45.356071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89734f39cd32'
down_revision = '3c454746626d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=128), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('requested_by', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('message', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_feedbacks', schema=None) as batch_op:
        batch_op.create_index('idx_orderfeedback_created', ['created_at'], unique=False)
        batch_op.create_index('idx_orderfeedback_employee_type', ['employee_id', 'type'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_feedbacks_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_feedbacks_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_feedbacks_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_feedbacks_type'), ['type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_feedbacks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_feedbacks_type'))
        batch_op.drop_index(batch_op.f('ix_order_feedbacks_order_id'))
        batch_op.drop_index(batch_op.f('ix_order_feedbacks_employee_id'))
        batch_op.drop_index(batch_op.f('ix_order_feedbacks_created_at'))
        batch_op.drop_index('idx_orderfeedback_employee_type')
        batch_op.drop_index('idx_orderfeedback_created')

    op.drop_table('order_feedbacks')
    op.drop_table('order_request')
    # ### end Alembic commands ###
