"""Fix Order model indexes

Revision ID: 960adfd5b91f
Revises: 28ddeec60e36
Create Date: 2025-07-08 14:44:22.630416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '960adfd5b91f'
down_revision = '28ddeec60e36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iot_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('device_type', sa.String(length=32), nullable=False),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qsc_inspections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('inspector_id', sa.Integer(), nullable=False),
    sa.Column('inspection_date', sa.Date(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=True),
    sa.Column('earned_points', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qsc_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_rooms',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('room_type', sa.String(length=20), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iot_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('data_type', sa.String(length=32), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['iot_devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('iot_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_iot_data_timestamp'), ['timestamp'], unique=False)

    op.create_table('qsc_inspection_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('is_passed', sa.Boolean(), nullable=False),
    sa.Column('points_earned', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('photos', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['inspection_id'], ['qsc_inspections.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['qsc_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('room_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('message_type', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['chat_rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('last_read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['chat_rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'user_id', name='_room_user_uc')
    )
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.create_index('idx_attendance_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('idx_notification_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_notification_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index('idx_order_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_order_date_status', ['created_at', 'status'], unique=False)
        batch_op.create_index('idx_order_employee_id', ['employee_id'], unique=False)
        batch_op.create_index('idx_order_status', ['status'], unique=False)
        batch_op.create_index('idx_order_store_id', ['store_id'], unique=False)

    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.create_index('idx_schedule_branch_id', ['branch_id'], unique=False)
        batch_op.create_index('idx_schedule_date', ['date'], unique=False)
        batch_op.create_index('idx_schedule_date_user', ['date', 'user_id'], unique=False)
        batch_op.create_index('idx_schedule_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_user_branch_id', ['branch_id'], unique=False)
        batch_op.create_index('idx_user_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_user_email', ['email'], unique=False)
        batch_op.create_index('idx_user_role', ['role'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('idx_user_role')
        batch_op.drop_index('idx_user_email')
        batch_op.drop_index('idx_user_created_at')
        batch_op.drop_index('idx_user_branch_id')

    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_index('idx_schedule_user_id')
        batch_op.drop_index('idx_schedule_date_user')
        batch_op.drop_index('idx_schedule_date')
        batch_op.drop_index('idx_schedule_branch_id')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index('idx_order_store_id')
        batch_op.drop_index('idx_order_status')
        batch_op.drop_index('idx_order_employee_id')
        batch_op.drop_index('idx_order_date_status')
        batch_op.drop_index('idx_order_created_at')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('idx_notification_user_id')
        batch_op.drop_index('idx_notification_created_at')

    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.drop_index('idx_attendance_user_id')

    op.drop_table('chat_participants')
    op.drop_table('chat_messages')
    op.drop_table('qsc_inspection_details')
    with op.batch_alter_table('iot_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_iot_data_timestamp'))

    op.drop_table('iot_data')
    op.drop_table('chat_rooms')
    op.drop_table('qsc_items')
    op.drop_table('qsc_inspections')
    op.drop_table('iot_devices')
    # ### end Alembic commands ###
