"""Add staff, contract, and health certificate models

Revision ID: a08fedabe0c4
Revises: 03759f934af2
Create Date: 2025-07-05 20:18:27.750311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a08fedabe0c4'
down_revision = '03759f934af2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('position', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('join_date', sa.Date(), nullable=False),
    sa.Column('salary', sa.String(length=50), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staff_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_restaurant_id'), ['restaurant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_user_id'), ['user_id'], unique=False)

    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('contract_number', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('renewal_date', sa.Date(), nullable=False),
    sa.Column('contract_type', sa.String(length=50), nullable=True),
    sa.Column('salary_amount', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('notification_sent', sa.Boolean(), nullable=True),
    sa.Column('expired_notification_sent', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_number')
    )
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.create_index('idx_contract_expired_notification', ['expiry_date', 'expired_notification_sent'], unique=False)
        batch_op.create_index('idx_contract_expiry_notification', ['expiry_date', 'notification_sent'], unique=False)
        batch_op.create_index(batch_op.f('ix_contracts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_contracts_expired_notification_sent'), ['expired_notification_sent'], unique=False)
        batch_op.create_index(batch_op.f('ix_contracts_expiry_date'), ['expiry_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_contracts_notification_sent'), ['notification_sent'], unique=False)
        batch_op.create_index(batch_op.f('ix_contracts_staff_id'), ['staff_id'], unique=False)

    op.create_table('health_certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('certificate_number', sa.String(length=50), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('renewal_date', sa.Date(), nullable=False),
    sa.Column('issuing_authority', sa.String(length=100), nullable=True),
    sa.Column('certificate_type', sa.String(length=50), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('notification_sent', sa.Boolean(), nullable=True),
    sa.Column('expired_notification_sent', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('certificate_number')
    )
    with op.batch_alter_table('health_certificates', schema=None) as batch_op:
        batch_op.create_index('idx_health_cert_expired_notification', ['expiry_date', 'expired_notification_sent'], unique=False)
        batch_op.create_index('idx_health_cert_expiry_notification', ['expiry_date', 'notification_sent'], unique=False)
        batch_op.create_index(batch_op.f('ix_health_certificates_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_health_certificates_expired_notification_sent'), ['expired_notification_sent'], unique=False)
        batch_op.create_index(batch_op.f('ix_health_certificates_expiry_date'), ['expiry_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_health_certificates_notification_sent'), ['notification_sent'], unique=False)
        batch_op.create_index(batch_op.f('ix_health_certificates_staff_id'), ['staff_id'], unique=False)

    with op.batch_alter_table('payrolls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_payroll_user_period'))
        batch_op.drop_constraint(batch_op.f('uq_user_year_month'), type_='unique')
        batch_op.create_index('idx_payroll_user_year_month', ['user_id', 'year', 'month'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payrolls', schema=None) as batch_op:
        batch_op.drop_index('idx_payroll_user_year_month')
        batch_op.create_unique_constraint(batch_op.f('uq_user_year_month'), ['user_id', 'year', 'month'])
        batch_op.create_index(batch_op.f('idx_payroll_user_period'), ['user_id', 'year', 'month'], unique=False)

    with op.batch_alter_table('health_certificates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_health_certificates_staff_id'))
        batch_op.drop_index(batch_op.f('ix_health_certificates_notification_sent'))
        batch_op.drop_index(batch_op.f('ix_health_certificates_expiry_date'))
        batch_op.drop_index(batch_op.f('ix_health_certificates_expired_notification_sent'))
        batch_op.drop_index(batch_op.f('ix_health_certificates_created_at'))
        batch_op.drop_index('idx_health_cert_expiry_notification')
        batch_op.drop_index('idx_health_cert_expired_notification')

    op.drop_table('health_certificates')
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contracts_staff_id'))
        batch_op.drop_index(batch_op.f('ix_contracts_notification_sent'))
        batch_op.drop_index(batch_op.f('ix_contracts_expiry_date'))
        batch_op.drop_index(batch_op.f('ix_contracts_expired_notification_sent'))
        batch_op.drop_index(batch_op.f('ix_contracts_created_at'))
        batch_op.drop_index('idx_contract_expiry_notification')
        batch_op.drop_index('idx_contract_expired_notification')

    op.drop_table('contracts')
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staff_user_id'))
        batch_op.drop_index(batch_op.f('ix_staff_status'))
        batch_op.drop_index(batch_op.f('ix_staff_restaurant_id'))
        batch_op.drop_index(batch_op.f('ix_staff_created_at'))

    op.drop_table('staff')
    # ### end Alembic commands ###
