"""Add attendance dispute model

Revision ID: add_attendance_dispute_model
Revises: 11ef276d8ea8
Create Date: 2025-01-27 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_attendance_dispute_model'
down_revision = '11ef276d8ea8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_disputes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attendance_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dispute_type', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('admin_reply', sa.Text(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['attendance_id'], ['attendances.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_disputes_created_at'), 'attendance_disputes', ['created_at'], unique=False)
    op.create_index(op.f('ix_attendance_disputes_status'), 'attendance_disputes', ['status'], unique=False)
    op.create_index(op.f('ix_attendance_disputes_user_id'), 'attendance_disputes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_disputes_user_id'), table_name='attendance_disputes')
    op.drop_index(op.f('ix_attendance_disputes_status'), table_name='attendance_disputes')
    op.drop_index(op.f('ix_attendance_disputes_created_at'), table_name='attendance_disputes')
    op.drop_table('attendance_disputes')
    # ### end Alembic commands ### 