"""add brand onboarding tables

Revision ID: add_brand_onboarding_tables
Revises: afae526cfff1
Create Date: 2025-07-15 12:30:00.000000

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = "add_brand_onboarding_tables"
down_revision = "afae526cfff1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "brand_onboarding",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("brand_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("step_store", sa.Boolean(), nullable=True),
        sa.Column("step_employee", sa.Boolean(), nullable=True),
        sa.Column("step_menu", sa.Boolean(), nullable=True),
        sa.Column("step_settings", sa.Boolean(), nullable=True),
        sa.Column("step_completed", sa.Boolean(), nullable=True),
        sa.Column("onboarding_data", sqlite.JSON, nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("last_activity", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brands.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("brand_onboarding", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_brand_onboarding_brand_id"), ["brand_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_brand_onboarding_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "onboarding_templates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("industry_id", sa.Integer(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("store_template", sqlite.JSON, nullable=True),
        sa.Column("employee_template", sqlite.JSON, nullable=True),
        sa.Column("menu_template", sqlite.JSON, nullable=True),
        sa.Column("settings_template", sqlite.JSON, nullable=True),
        sa.Column("is_default", sa.Boolean(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["industry_id"],
            ["industries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("onboarding_templates")
    with op.batch_alter_table("brand_onboarding", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_brand_onboarding_user_id"))
        batch_op.drop_index(batch_op.f("ix_brand_onboarding_brand_id"))
    op.drop_table("brand_onboarding")
    # ### end Alembic commands ###
