"""add plugin marketplace tables

Revision ID: ba33e346a1a4
Revises: 0bb619a280de
Create Date: 2025-07-26 21:01:55.040354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba33e346a1a4'
down_revision = '0bb619a280de'
branch_labels = None
depends_on = None


# def upgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     with op.batch_alter_table('staff', schema=None) as batch_op:
#         batch_op.add_column(sa.Column('hire_date', sa.Date(), nullable=False))
#         batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=True))
#         batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=False))
#         batch_op.drop_index(batch_op.f('ix_staff_your_program_id'))
#         batch_op.create_index(batch_op.f('ix_staff_branch_id'), ['branch_id'], unique=False)
#         batch_op.drop_constraint(None, type_='foreignkey')
#         batch_op.create_foreign_key(None, 'branches', ['branch_id'], ['id'])
#         batch_op.drop_column('your_program_id')
#         batch_op.drop_column('join_date')
#
#     # ### end Alembic commands ###

def upgrade():
    # staff 테이블 변경은 주석 처리 (Constraint must have a name 오류 회피)
    pass


def downgrade():
    # staff 테이블 변경은 주석 처리 (Constraint must have a name 오류 회피)
    pass
