"""Add position field to User model

Revision ID: c42569c9af83
Revises: 6d07eca14f89
Create Date: 2025-07-06 18:26:32.584706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c42569c9af83'
down_revision = '6d07eca14f89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_position'), ['position'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_position'))
        batch_op.drop_column('position')

    # ### end Alembic commands ###
