"""Add manager_id to Branch model

Revision ID: e19cdaecc83e
Revises: 
Create Date: 2025-07-26 17:27:44.319818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e19cdaecc83e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manager_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_branches_manager_id'), ['manager_id'], unique=False)
        batch_op.create_foreign_key('fk_branches_manager_id_users', 'users', ['manager_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.drop_constraint('fk_branches_manager_id_users', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_branches_manager_id'))
        batch_op.drop_column('manager_id')

    # ### end Alembic commands ###
