"""init

Revision ID: f91f70efbdaf
Revises: b4ecea7fa3d5
Create Date: 2025-06-27 19:22:17.936345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f91f70efbdaf'
down_revision = 'b4ecea7fa3d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_notifications')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('recipient_role',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('recipient_team',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('priority',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=10),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('ai_priority',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=10),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.drop_index('idx_notification_admin_only')
        batch_op.drop_index('idx_notification_user_category')
        batch_op.create_index('idx_notification_priority_date', ['priority', 'created_at'], unique=False)
        batch_op.create_index('idx_notification_team_role', ['recipient_team', 'recipient_role'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_ai_priority'), ['ai_priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_priority'), ['priority'], unique=False)

    with op.batch_alter_table('reason_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True, comment='승인 상태: pending/approved/rejected'))
        batch_op.add_column(sa.Column('approved_by', sa.Integer(), nullable=True, comment='승인자'))
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(), nullable=True, comment='승인일시'))
        batch_op.add_column(sa.Column('approval_comment', sa.String(length=200), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_unique_constraint('uq_reason_templates_text', ['text'])
        batch_op.create_foreign_key('fk_reason_templates_approved_by', 'users', ['approved_by'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('permissions', sa.JSON(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_team_id'), ['team_id'], unique=False)
        batch_op.create_foreign_key('fk_users_team_id', 'teams', ['team_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_team_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_users_team_id'))
        batch_op.drop_column('permissions')
        batch_op.drop_column('team_id')

    with op.batch_alter_table('reason_templates', schema=None) as batch_op:
        batch_op.drop_constraint('fk_reason_templates_approved_by', type_='foreignkey')
        batch_op.drop_constraint('uq_reason_templates_text', type_='unique')
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('approval_comment')
        batch_op.drop_column('approved_at')
        batch_op.drop_column('approved_by')
        batch_op.drop_column('status')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_priority'))
        batch_op.drop_index(batch_op.f('ix_notifications_ai_priority'))
        batch_op.drop_index('idx_notification_team_role')
        batch_op.drop_index('idx_notification_priority_date')
        batch_op.create_index('idx_notification_user_category', ['user_id', 'category'], unique=False)
        batch_op.create_index('idx_notification_admin_only', ['is_admin_only', 'created_at'], unique=False)
        batch_op.alter_column('ai_priority',
               existing_type=sa.String(length=10),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('priority',
               existing_type=sa.String(length=10),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('recipient_team',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('recipient_role',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)

    op.create_table('_alembic_tmp_notifications',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.VARCHAR(length=255), nullable=False),
    sa.Column('related_url', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), nullable=True),
    sa.Column('category', sa.VARCHAR(length=50), nullable=False),
    sa.Column('link', sa.VARCHAR(length=255), nullable=True),
    sa.Column('is_admin_only', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True),
    sa.Column('recipient_role', sa.VARCHAR(length=20), nullable=True),
    sa.Column('recipient_team', sa.VARCHAR(length=20), nullable=True),
    sa.Column('priority', sa.VARCHAR(length=10), server_default=sa.text('0'), nullable=True),
    sa.Column('ai_priority', sa.VARCHAR(length=10), server_default=sa.text('0'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
