"""통합 스케줄 모델 - 근무/청소 구분

Revision ID: fb8a2391b767
Revises: 89734f39cd32
Create Date: 2025-06-29 14:08:33.644235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb8a2391b767'
down_revision = '89734f39cd32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('type', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('team', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('plan', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('manager_id', sa.Integer(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key('fk_schedule_manager_id', 'users', ['manager_id'], ['id'])
        batch_op.create_foreign_key('fk_schedule_branch_id', 'branches', ['branch_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_constraint('fk_schedule_manager_id', type_='foreignkey')
        batch_op.drop_constraint('fk_schedule_branch_id', type_='foreignkey')
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('manager_id')
        batch_op.drop_column('plan')
        batch_op.drop_column('team')
        batch_op.drop_column('type')
        batch_op.drop_column('branch_id')

    # ### end Alembic commands ###
