"""Rename Notification is_read to read

Revision ID: ff5e0a1bfdb0
Revises: 77097a1f5019
Create Date: 2025-06-22 15:29:11.036348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff5e0a1bfdb0'
down_revision = '77097a1f5019'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read', sa.Boolean(), nullable=True))
        batch_op.drop_index('ix_notifications_is_read')
        batch_op.drop_index('idx_notification_user_read')
        batch_op.create_index('idx_notification_user_read', ['user_id', 'read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_read'), ['read'], unique=False)
        batch_op.drop_column('is_read')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_read', sa.BOOLEAN(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_notifications_read'))
        batch_op.drop_index('idx_notification_user_read')
        batch_op.create_index('idx_notification_user_read', ['user_id', 'is_read'], unique=False)
        batch_op.create_index('ix_notifications_is_read', ['is_read'], unique=False)
        batch_op.drop_column('read')

    # ### end Alembic commands ###
